---
- hosts: localhost
  gather_facts: no
  vars:
    var_vmname: "TestFromAnsible1"
    var_proxmox_node: "old-steady"
  tasks:
  - include_vars: private_proxmox_vars.yml
  - name: Create new VM with minimal options
    community.general.proxmox_kvm:
      api_user: "{{ gbl_prox_api_user }}"
      api_password: "{{ gbl_prox_api_pw }}"
      api_host: "{{ gbl_prox_api_host }}"
      name: "{{ var_vmname }}"
      node: "{{ var_proxmox_node }}"
      state: present
      timeout: 300
      cores: 1
      memory: 2048
      boot: d
      ide: '{"ide0":"SASPOOL-ISO:iso/ubuntu-20.04-live-server-amd64.iso,media=cdrom"}'
      virtio: '{"virtio0":"Saspool-VM:12"}'
      net:
        net0: 'virtio,bridge=vmbr2'
    register: wait

  - name: Let it settle
    pause:
      seconds: 5

  - name: Start the new ProxMox VM
    proxmox_kvm:
      api_user: "{{ gbl_prox_api_user }}"
      api_password: "{{ gbl_prox_api_pw }}"
      api_host: "{{ gbl_prox_api_host }}"
      name: "{{ var_vmname }}"
      node: "{{ var_proxmox_node }}"
      state: started      