---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root

  tasks:
    - name: Create a virtual machine on given ESXi host
      vmware_guest:
        hostname: "{{ ian_esxi_hostAddr }}"
        username: "{{ ian_esxi_username }}"
        password: "{{ ian_esxi_pw }}"
        datacenter: ha-datacenter
        validate_certs: no
        folder: ''
        name: test_vm_0001
        state: poweredon
        guest_id: ubuntu64Guest
        # This is hostname of particular ESXi server on which user wants VM to be deployed
        disk:
        - size_gb: 10
          type: thin
          datastore: DS1
        hardware:
          memory_mb: 512
          num_cpus: 4
          scsi: paravirtual
        networks:
        - name: VM Network
          device_type: vmxnet3
      delegate_to: localhost
      register: deploy_vm